name: Laravel pint
on:
    pull_request
jobs:
    laravel-pint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup PHP and Composer
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                tools: composer:v2

            - name: Install Laravel Pint
              run: composer global require laravel/pint

            - name: Run Pint
              run: pint

            - name: Push changes to repo
              run: |
                  git config user.name 'gh-actions'
                  git config user.email 'gh@actions.com'
                  git add .
                  git commit -m 'Laravel Pint fixes' || exit 0
                  git push
